env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/warnings

parser: babel-eslint

parserOptions:
  ecmaVersion: 9
  sourceType: module

globals:
  html: readonly
  dhtml: readonly
  rhtml: readonly
  svg: readonly
  dsvg: readonly
  rsvg: readonly

rules:
  semi: error
  no-unused-vars:
    - error
    - varsIgnorePattern: ^hs?|ds?$
