sudo: false

language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

addons:
  sauce_connect: true

script:
  - COVERAGE=true yarn test --single-run

after_success:
  - yarn run coverage

git:
  submodules: false
